version: '3.9'
services:
  mongodb:
    image: mongo:4.4
    restart: always
    ports:
      - "27025:27017"
    networks:
      - mongonetwork
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/rabbitmq_definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - rabbitnetwork
  api-locadora:
    image: locadora-carro-api:1.00
    container_name: api-locadora
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - rabbitnetwork
      - mongonetwork
networks:
  rabbitnetwork:
    driver: bridge
  mongonetwork:
    driver: bridge

